name: u_puli_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: "none"

environment:
  sdk: ^3.5.4

dependencies:
  args: ^2.4.0
  equatable: ^2.0.7
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  # drift: ^2.25.1
  # drift_postgres: ^1.3.0
  # postgres: ^3.5.4
  mocktail: ^1.0.4
  get_it: ^8.0.3
  database_wrapper:
    path: ./packages/database_wrapper
  env_vars_wrapper:
    path: ./packages/env_vars_wrapper

dev_dependencies:
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
  # drift_dev: ^2.25.2
  build_runner: ^2.4.15
