// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    eventEntity,
  ];
  late final Shape0 eventEntity = Shape0(
      source: i0.VersionedTable(
        entityName: 'event_entity',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(title, date, location)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get date =>
      columnsByName['date']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get location =>
      columnsByName['location']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>('id', aliasedName, false,
        hasAutoIncrement: true, type: i1.DriftSqlType.int);
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>('title', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<DateTime> _column_2(String aliasedName) =>
    i1.GeneratedColumn<DateTime>('date', aliasedName, false,
        type: i1.DriftSqlType.dateTime);
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>('location', aliasedName, false,
        type: i1.DriftSqlType.string);

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    eventEntity,
    authEntity,
  ];
  late final Shape0 eventEntity = Shape0(
      source: i0.VersionedTable(
        entityName: 'event_entity',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(title, date, location)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 authEntity = Shape1(
      source: i0.VersionedTable(
        entityName: 'auth_entity',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_4,
          _column_5,
          _column_6,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get email =>
      columnsByName['email']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get password =>
      columnsByName['password']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get authType =>
      columnsByName['auth_type']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>('email', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>('password', aliasedName, true,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>('auth_type', aliasedName, false,
        type: i1.DriftSqlType.int);

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    eventEntity,
    authEntity,
    userEntity,
  ];
  late final Shape0 eventEntity = Shape0(
      source: i0.VersionedTable(
        entityName: 'event_entity',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(title, date, location)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 authEntity = Shape1(
      source: i0.VersionedTable(
        entityName: 'auth_entity',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_4,
          _column_5,
          _column_6,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 userEntity = Shape2(
      source: i0.VersionedTable(
        entityName: 'user_entity',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'FOREIGN KEY (auth_id) REFERENCES auth_entity(id)',
        ],
        columns: [
          _column_0,
          _column_7,
          _column_8,
          _column_9,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get firstName =>
      columnsByName['first_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastName =>
      columnsByName['last_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get authId =>
      columnsByName['auth_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>('first_name', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>('last_name', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>('auth_id', aliasedName, false,
        type: i1.DriftSqlType.int);

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    eventEntity,
    authEntity,
    userEntity,
    userEntityAuthIdIdx,
  ];
  late final Shape0 eventEntity = Shape0(
      source: i0.VersionedTable(
        entityName: 'event_entity',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(title, date, location)',
        ],
        columns: [
          _column_10,
          _column_1,
          _column_2,
          _column_3,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 authEntity = Shape1(
      source: i0.VersionedTable(
        entityName: 'auth_entity',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_10,
          _column_11,
          _column_5,
          _column_6,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 userEntity = Shape2(
      source: i0.VersionedTable(
        entityName: 'user_entity',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'FOREIGN KEY (auth_id) REFERENCES auth_entity(id)',
        ],
        columns: [
          _column_10,
          _column_7,
          _column_8,
          _column_9,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  final i1.Index userEntityAuthIdIdx = i1.Index('user_entity_auth_id_idx',
      'CREATE INDEX user_entity_auth_id_idx ON user_entity (auth_id)');
}

i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>('id', aliasedName, false,
        hasAutoIncrement: true,
        type: i1.DriftSqlType.int,
        defaultConstraints:
            i1.GeneratedColumn.constraintIsAlways('PRIMARY KEY AUTOINCREMENT'));
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>('email', aliasedName, false,
        type: i1.DriftSqlType.string,
        defaultConstraints: i1.GeneratedColumn.constraintIsAlways('UNIQUE'));

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    eventEntity,
    authEntity,
    userEntity,
    userEntityAuthIdIdx,
  ];
  late final Shape3 eventEntity = Shape3(
      source: i0.VersionedTable(
        entityName: 'event_entity',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(title, date, location)',
        ],
        columns: [
          _column_10,
          _column_1,
          _column_2,
          _column_3,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 authEntity = Shape1(
      source: i0.VersionedTable(
        entityName: 'auth_entity',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_10,
          _column_11,
          _column_5,
          _column_6,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 userEntity = Shape2(
      source: i0.VersionedTable(
        entityName: 'user_entity',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'FOREIGN KEY (auth_id) REFERENCES auth_entity(id)',
        ],
        columns: [
          _column_10,
          _column_7,
          _column_8,
          _column_9,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  final i1.Index userEntityAuthIdIdx = i1.Index('user_entity_auth_id_idx',
      'CREATE INDEX user_entity_auth_id_idx ON user_entity (auth_id)');
}

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get date =>
      columnsByName['date']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get location =>
      columnsByName['location']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get url =>
      columnsByName['url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get imageUrl =>
      columnsByName['image_url']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>('url', aliasedName, false,
        type: i1.DriftSqlType.string);
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>('image_url', aliasedName, false,
        type: i1.DriftSqlType.string);

final class Schema7 extends i0.VersionedSchema {
  Schema7({required super.database}) : super(version: 7);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    eventEntity,
    authEntity,
    userEntity,
    userEntityAuthIdIdx,
  ];
  late final Shape3 eventEntity = Shape3(
      source: i0.VersionedTable(
        entityName: 'event_entity',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(title, date, location, url, image_url)',
        ],
        columns: [
          _column_10,
          _column_1,
          _column_2,
          _column_3,
          _column_12,
          _column_13,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 authEntity = Shape1(
      source: i0.VersionedTable(
        entityName: 'auth_entity',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_10,
          _column_11,
          _column_5,
          _column_6,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 userEntity = Shape2(
      source: i0.VersionedTable(
        entityName: 'user_entity',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'FOREIGN KEY (auth_id) REFERENCES auth_entity(id)',
        ],
        columns: [
          _column_10,
          _column_7,
          _column_8,
          _column_9,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  final i1.Index userEntityAuthIdIdx = i1.Index('user_entity_auth_id_idx',
      'CREATE INDEX user_entity_auth_id_idx ON user_entity (auth_id)');
}

i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      case 6:
        final schema = Schema7(database: database);
        final migrator = i1.Migrator(database, schema);
        await from6To7(migrator, schema);
        return 7;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
}) =>
    i0.VersionedSchema.stepByStepHelper(
        step: migrationSteps(
      from1To2: from1To2,
      from2To3: from2To3,
      from3To4: from3To4,
      from4To5: from4To5,
      from5To6: from5To6,
      from6To7: from6To7,
    ));
